#!/usr/bin/python

import subprocess, sys

addr = sys.argv[1]

port = '12345'

sproc = subprocess.Popen(['ssh','-D',port,addr])

chrom = subprocess.Popen(['chromium-browser','--proxy-server=socks5://localhost:'+port])
chrom.wait()    

sproc.kill()

