#!/usr/bin/python

import sys, os
dirname = os.path.abspath(sys.argv[1])

filename = os.path.join(dirname,os.path.basename(dirname)+".Rproj")
print filename

if os.path.exists(filename):
    print "Already blessed"
else:
    with open(filename, "wt") as f:
        print >> f, """\
Version: 1.0

RestoreWorkspace: Default
SaveWorkspace: Default
AlwaysSaveHistory: Default

EnableCodeIndexing: Yes
UseSpacesForTab: Yes
NumSpacesForTab: 4
Encoding: UTF-8

RnwWeave: Sweave
LaTeX: pdfLaTeX"""



filename = os.path.join(dirname,os.path.basename(dirname)+".sublime-project")
print filename
if os.path.exists(filename):
    print "Already a sublime project"
else:
    with open(filename, "wt") as f:
        print >> f, """\
{
    "folders" : [ { "path" : "." } ]
}"""

