#!/usr/bin/env python3

import sys,os

def explore(path, max_size, max_dir):
    total = 0
    items = os.listdir(path)
    if len(items) > max_dir: 
        print("Skip "+path, file=sys.stderr)
        return 0
    
    for item in items:
        full = os.path.join(path, item)
        assert "\n" not in item
        if os.path.islink(full):
            print(full)
        elif os.path.isfile(full):
            size = os.path.getsize(full)
            if size <= max_size:
                print(full)
                total += size
        elif os.path.isdir(full):
            total += explore(full, max_size, max_dir)
    
    return total

[ max_size, max_dir, *paths ] = sys.argv[1:]
max_size = float(max_size) * (1<<20)
max_dir = int(max_dir)

total = 0
for path in paths:
    total += explore(os.path.abspath(path), max_size, max_dir)
print(str(total / (1<<20)) + " MB", file=sys.stderr)
