#!/usr/bin/env python

import sys, os, time, socket

def background(command):
    os.system('nohup ' + command + ' >/dev/null 2>/dev/null &')

n = os.getuid() % 1000 + 1
os.environ['DISPLAY'] = ':%d' % n

def running():
    return os.system('xset q >/dev/null 2>/dev/null') == 0

if not running():
    #background('Xtightvnc :%d -localhost -desktop X -depth 24 -dpi 100'
    #           ' -geometry 3840x1080' % n)
    background('Xtightvnc :%d -localhost -desktop X -depth 24 -dpi 200'
               ' -geometry 2560x1600' % n)
    
    print >> sys.stderr, 'Wait for server to start'
    while not running():
       time.sleep(0.1)
    
    background("lxsession")

me = socket.gethostbyaddr(socket.gethostname())[0]

print 'xtightvncviewer -x11cursor -via %s :%d' % (me, n)

