#!/usr/bin/python

import sys, os
dirname = os.path.abspath(sys.argv[1] if len(sys.argv) > 1 else ".")

filename = os.path.join(dirname,os.path.basename(dirname)+".sublime-project")
os.system("subl --project "+filename)

